[package]
edition = "2021"
name = "seed-bindgen"
version = "0.1.0"

[dependencies]
console_error_panic_hook = "0.1.6"
js-sys = "0.3.64"
secrecy = { version = "0.8.0" }
seed-core = { workspace = true }
wasm-bindgen = "0.2.58"

[dev-dependencies]
wasm-bindgen-test = "0.3.0"
